######################################################################
# Automatically generated by qmake (3.0) Mon Nov 9 10:43:21 2015
######################################################################

TEMPLATE = app
TARGET = c_imageviewer
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += window.h
SOURCES += ImageList.cc test.cc window.cc
