######################################################################
# Automatically generated by qmake (3.0) Mon Nov 9 10:43:21 2015
######################################################################

TEMPLATE = app
TARGET = viewer
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += Viewer.h
SOURCES += ImageList.cc main.cc Viewer.cc
